### ISSUE TITLE
complete circle to finish running meta-analysis

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#269]
- [x] add nimads module to read in studysets and annotations from neurosynth-compose into NiMARE
- [x] convert nimads studyset to NiMARE dataset
- [x] export specification from neurosynth-compose
- [x] translate specification from json to a NIMARE workflow
- [x] create function to download studyset/annotation/specification in NiMARE
- [ ] upload results back to neurostore
- [ ] tie results to meta-analysis

**Comment by jdkent** [comment]
final upload part related to #283
