### ISSUE TITLE
move required items from meta-data to top level study fields

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#83]

**Comment by jdkent** [comment]
potential kets (that have over 50% usage that could be put into the main study description:
- [ ] 'DOI'
- [ ] ~~'add_date'~~: already represented with `created_at`
- [ ] 'authors'
- [ ] ~~'description'~~: already represented
- [ ] 'doi_add_date'
- [ ] ~~'download_url'~~: specific download link for neurovault
- [ ] ~~'id'~~: already represented
- [ ] 'journal_name'
- [ ] ~~'modify_date'~~: already represented with `updated_at`
- [ ] ~~'name'~~: already represented
- [ ] 'number_of_images'
- [ ] ~~'owner'~~: already represented with `user`
- [ ] 'owner_name'
- [ ] 'paper_url'
- [ ] ~~'url'~~: represented by `source_id`

**Comment by jdkent** [comment]
closed with #95
